# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\AppleZhang_Workshop\Codes\CW\udp_chatroom_ver0.3\pyqt_desktop\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(279, 183)
        Dialog.setToolTipDuration(1)
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(30, 30, 58, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.nameLabel.setFont(font)
        self.nameLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.nameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.nameInput = QtWidgets.QLineEdit(Dialog)
        self.nameInput.setGeometry(QtCore.QRect(110, 30, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.nameInput.setFont(font)
        self.nameInput.setObjectName("nameInput")
        self.passLabel = QtWidgets.QLabel(Dialog)
        self.passLabel.setGeometry(QtCore.QRect(30, 70, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.passLabel.setFont(font)
        self.passLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.passLabel.setMouseTracking(False)
        self.passLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passLabel.setObjectName("passLabel")
        self.passInput = QtWidgets.QLineEdit(Dialog)
        self.passInput.setGeometry(QtCore.QRect(110, 70, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.passInput.setFont(font)
        self.passInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passInput.setObjectName("passInput")
        self.submitButton = QtWidgets.QPushButton(Dialog)
        self.submitButton.setGeometry(QtCore.QRect(50, 110, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.submitButton.setFont(font)
        self.submitButton.setObjectName("submitButton")
        self.exitButton = QtWidgets.QPushButton(Dialog)
        self.exitButton.setGeometry(QtCore.QRect(150, 110, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.noticeLabel = QtWidgets.QLabel(Dialog)
        self.noticeLabel.setGeometry(QtCore.QRect(10, 140, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.noticeLabel.setFont(font)
        self.noticeLabel.setTextFormat(QtCore.Qt.PlainText)
        self.noticeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noticeLabel.setObjectName("noticeLabel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chatroom"))
        self.nameLabel.setText(_translate("Dialog", "Username"))
        self.passLabel.setText(_translate("Dialog", "Password"))
        self.submitButton.setText(_translate("Dialog", "Login"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.noticeLabel.setText(_translate("Dialog", "Please enter username and password"))
